### ISSUE TITLE
MZDPI-screen

### ISSUE THREAD

**Issue by uav-profile** [paulloft/raspberry#1]
Hi, I used your script on Raspberry Pi 4. The picture appeared, but at the "Starting File System" stage it freezes, nothing happens. Tell me, please, what is the problem?

**Comment by paulloft** [comment]
Hi, I apologize for the long reply, I did not receive a notification. Could you solve your problem?

Unfortunately, I can not check the script for anything other than raspberry zero, because the display is soldered to it.

**Comment by tinman9000** [comment]
I am also having the same issue, after the script is run and the pi is rebooted, I get a flash of the loader image starting up then black screen after, is there more to the install script other then what's on the read me ?
